# Generated by Django 3.2.6 on 2022-06-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220615_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelinfostage',
            name='description',
        ),
    ]
